version: '3.4'

services:
  foodapi:
    image: ${DOCKER_REGISTRY-}foodapi
    build:
      context: .
      dockerfile: FoodAPI/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'root'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "FoodApi@"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '1433:1433'    
    expose:
      - 1433
